feat: add mutual friends
decentraland/matrix-client pull request #132
Opened 2023-02-15 16:59 UTC by Julieta11

2023-02-15 20:05 UTC, moliva commented on src/FriendsManagementClient.ts
> +export async function getFriendsFromSocialService(baseUrl: string, userId: string, auth: string): Promise<string[]> {
Let's use this opportunity to add docs to this function as well.

2023-02-15 20:05 UTC, moliva commented on test/unit/socialServerMock.ts
> +        }
Let's wrap the logic of the `if (isValidToken) { ... } else { res.sendStatus(401) }` as another function. WDYT?

2023-02-28 16:06 UTC, agusaldasoro requested changes

2023-02-28 16:06 UTC, agusaldasoro commented on src/FriendsManagementClient.ts
> +    const url = new URL(`${baseUrl}/v1/friendships/${userId}`)
can you change this to use `/friendships/me`? So we don't have to send the userId as param

2023-02-28 16:32 UTC, jmoguilevsky approved these changes

2023-03-02 17:44 UTC, merged

2023-03-02 17:55 UTC, moliva commented
:tada: This PR is included in version 1.25.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/dcl-social-client/v/1.25.0)
- [GitHub release](https://github.com/decentraland/matrix-client/releases/tag/v1.25.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: